<?php importView("header.phtml"); ?><body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>


<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header"><span style="color: palevioletred;font-weight: bold">菠萝&蜜桃应用中心管理</span></div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">


                        <div class="layui-inline">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">

                            <label class="layui-form-label">短标识<a title="参考" href="<?php echo SYSTEM_SHARE_LINK; ?>">?</a>：</label>
                            <div class="layui-input-block">

                                <input  placeholder="短标识" name="short_name"
                                        value="{{=d.short_name }}" class="layui-input">

                            </div>

                        </div>

                        <div class="layui-inline">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <?php echo Layui::select('where[status]',
                                    merge_array(['' => '不限'], AdsAppModel::STATUS)) ?>
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                        <div class="layui-inline">
                            <span style="color: #FF5722"> 应用中心排序 数字越大越前面，数字跨越不要太大，100以内即可 </span>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <!--  <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>-->
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-h="780" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">

            <label class="layui-form-label">标题：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="标题" name="title"
                       value="{{=d.title }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">描述：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="描述" name="description"
                       value="{{=d.description }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">图标：</label>
            <div class="layui-input-block">


                <img src="{{d.img_url_full }}" id="img-img_url" width="50" height="50">
                <button type="button" class="but-upload-img layui-btn" data-json="{position:'ads'}"
                        data-img="#img-img_url" data-input="#input-img_url"><i class="layui-icon">&#xe67c;</i>上传
                </button>
                <input type="hidden" name="img_url" id="input-img_url" value="{{=d.img_url }}">
            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">跳转地址：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="跳转地址" name="link_url"
                       value="{{=d.link_url }}" class="layui-input">

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">状态：</label>
            <div class="layui-input-block">

                <?php echo Layui::select('status', AdsModel::STATUS, ['data-value' => '{{=d.status}}']) ?>

            </div>

        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">点击次数：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="点击次数" name="clicked"
                       value="{{=d.clicked }}" class="layui-input">

            </div>
        </div>


        <div class="layui-form-item">

            <label class="layui-form-label">排序：</label>
            <div class="layui-input-block">

                <input lay-verify="required" placeholder="排序" name="sort"
                       value="{{=d.sort }}" class="layui-input">

            </div>

        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id',width: 100}
            , {
                field: 'img_url', width: 120, title: '图片', align: 'center', templet: function (d) {
                    if(d.img_url){
                        return '<div onclick="show_img(\''+d.img_url_full+'\')" ><img width="50" src="' + d.img_url_full + '" /></div>';
                    }
                    return '';
                }
            }
            , {field: 'title', title: '标题',width: 150}
            , {field: 'description', title: '描述'}
            , {field: 'short_name', title: '分享标识',edit: true}
            , {field: 'status', title: '状态', type: "switch", "value": "1|0", edit: true,width: 120}
            , {field: 'sort', title: '排序', sort: true,width: 100,edit: true,}
            , {field: 'clicked', title: '点击', edit: true,width: 120}
            , {field: 'created_at', title: '创建',width: 120}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>