[www]
user = www-data
group = www-data

listen = 9000

pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20

slowlog = /var/log/fpm-slow.log
request_slowlog_timeout = 3

catch_workers_output = yes
clear_env = no

