<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {
        margin-right: 30px
    }</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header" style="color: orangered">待审核剧集管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                        <div class="layui-inline">
                            <label class="layui-form-label">ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="where[id]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <label class="layui-form-label">名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[title]" placeholder="请输入" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>

                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>

                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="800" data-h="600" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>待审核剧集管理</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">


        <div class="layui-form-item">
            <label class="layui-form-label">名称：</label>
            <div class="layui-input-block">
                <input disabled placeholder="名称"
                       value="{{=d.title }}" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">类型：</label>
            <div class="layui-input-inline">
                <input disabled placeholder="类型"
                       value="{{=d.type }}" class="layui-input">
            </div>
            <label class="layui-form-label">标签：</label>
            <div class="layui-input-inline">
                <input disabled placeholder="标签"
                       value="{{=d.tags }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">年份：</label>
            <div class="layui-input-inline">
                <input disabled placeholder="年份"
                       value="{{=d.year }}" class="layui-input">
            </div>
            <label class="layui-form-label">地区：</label>
            <div class="layui-input-inline">
                <input disabled placeholder="地区"
                       value="{{=d.area }}" class="layui-input">
            </div>

        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">描述：</label>
            <div class="layui-input-block">
                <textarea class="layui-textarea" disabled>{{=d.desp }}</textarea>
            </div>

        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">状态 ：</label>
            <div class="layui-input-block">
                <?php echo Layui::select('status', UserTopicModel::STAT, ['data-value' => '{{=d.status}}']) ?>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">理由：</label>
            <div class="layui-input-block">
                <input  placeholder="剧集未通过的简洁原因" name="deny_str"
                       value="{{=d.deny_str }}" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax",['where[status]'=>UserTopicModel::STAT_WAIT]) ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: '<?php echo url_backend("upload/upload") ?>',
        title: '数据表',
        pk: 'id',
        cols: [[
            {field: 'id', title: 'id', width: 100,sort:true}
            , {field: 'title', title: '名称'}
            , {field: 'uid', title: '用户'}
            , {
                field: 'image_url', title: '封面', width: 180, templet: function (d) {
                    if (d.image) {
                        return '<img src="' + d.image_url + '" style="width: 100px;height: 80px;" onclick="show_img(\'' + d.image_url + '\')">';
                    } else {
                        return '--';
                    }
                }
            }
            , {field: 'type', title: '类型'}
            , {field: 'tags', title: '标签'}
            , {field: 'year', title: '年份'}
            , {field: 'area', title: '地区'}
            //, {field: 'status_str', title: '状态'}
            , {fixed: 'right', width: 260, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>