[common]
application.dispatcher.throwException=1
application.dispatcher.catchException=1
application.directory = APP_PATH "/application"
application.bootstrap=APP_PATH "/application/bootstrap/Bootstrap.php"
application.modules = "Index,Home,Api,Admin,Script,V2,Live"
application.dispatcher.defaultModule = 'Home'
application.dispatcher.defaultController = 'Forward'
application.library.namespace = "App"
;user
user.default_filter='trim,addslashes,htmlspecialchars'
token.login=e096db7c006958f226bc469c27237345

img.img_av_url=https://images.91tv.tv/img.av/
img.img_live_url=https://images.91tv.tv/img.live/
img.img_xiao_url=https://images.91tv.tv/
img.img_actors_url=https://images.91tv.tv/img.actors/
img.img_head_url=https://images.91tv.tv/img.head/
img.img_ads_url=https://images.91tv.tv/img.ads/
img.img_icos_url=https://images.91tv.tv/img.icos/
img.img_music_url=https://p.cnkamax.com/
img.default_jd_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91nolog_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91login_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
;sms
sms.timeout=120
; user can watch count
; 页面
site.long_video_duration=30
site.can_watch_count = 10
template.compiled_root_path = /data/cache/tpl/
template.template_path = tpl
template.template_root_path = /theme/

; 远程配置
; cfg.json = "https://config.zxsnvvik.top/php-yuanc-share.json"
; cfg.site = "https://config.zxsnvvik.top/php-yuanc.json"
; 本部配置
cfg.json = "https://config.microservices.vip/2020090623125271421-share.json"
cfg.site = "https://config.microservices.vip/2020090623125271421.txxxx"

; 新Ai
ai_image_face.url = https://p0-api.inaiai.com
ai_image_face.key = abw3P9t1kpVhEh2TLLo7hNddA2brvNdj
; AI 图生视频
ai_magic.url = https://p0-api.inaiai.com
ai_magic.key = abw3P9t1kpVhEh2TLLo7hNddA2brvNdj
; AI 脱衣
ai_strip.url = https://p0-api.inaiai.com
ai_strip.key = abw3P9t1kpVhEh2TLLo7hNddA2brvNdj

;数据报表
extra.report.app_id =12
extra.report.ai.url=https://call-apk.yesebo.net/api.php/api/ai/report
extra.report.daily.url=https://call-apk.yesebo.net/api.php/api/daily/report
extra.report.sign=b7b3151e5ca96bf9ef5020a9e732ce38
extra.report.key=19ac039f52590ddd
extra.report.iv=fa984b2aef74b96c
extra.report.method=aes-128-cbc

;新客服系统
customer.app_id = 2139911417
customer.key = nROxUJRykKBqf0VJ
customer.api_url = https://coksapi.com

; 点击上报
;click.report.url = https://api.shuifeng.cc/api/eventTracking/batchReport.json
click.report.url = https://ap.dc-report.cc/api/eventTracking/batchReport.json
click.report.app_id = DX-031
channel.report.apk = https://union-api.hao123apps.info/api.php/api/channel/appinfo
click.report.secret = "qwMh8sop7e4io5Crao5ekOkzzd1jKWqqgkY9gH1FDjg"

;上报key
monitor.group_id = 69739d4927e4dc26da901e35
monitor.secret_key = aa22834da4d48aa6fddb74ac18410bbc

app_store_url = https://txt.dton.me

; remote ads
ads.key = oPvAx39yO6
ads.app.list.url = https://ads.microservices.vip/api/list
ads.app.report.url = https://ads.microservices.vip/api/click

;官方群
official.group='https://ptcc.in/gtvlive'
; 联盟id
union.pid=27
; 联盟加解密key
union.key="c9077f8c6268ccdfadf6ffddcgbsd2dg"
; 联盟签名key
union.sign="s745dkslfh4kihfks3kjdhfksjh3kdjf"
; 联盟消息存放在redis中的消息队列name
union.qname="serv:chan-queue"
;  日志等级。最高16，最低0，调试时使用16，正式环境日志等级使用 9 ，不需要日志 0
union.log_level=9
;r2分片上传配置
upload.r2URL = https://r2.microservices.vip/multipart_upload
upload.r2Key = d2bf7126723ea8f6005ba141ea3c3e2c
upload.r2CompleteURL = https://r2.microservices.vip/multipart_complete
[product : common]
;database
database.driver='mysql'
;master
database.write.host='192.168.137.237'
;slave-001
database.read.host='192.168.144.195'
database.port='3306'
database.database='bluegv'
database.username='db_gv_con'
database.password='Ufy=(kgtv8#G8mz'
database.charset='utf8mb4'
database.collation='utf8mb4_general_ci'
database.prefix='ks_'
database.strict=false
;redis
redis.host.0=192.168.137.97:7000
redis.host.1=192.168.128.20:7000
redis.host.2=192.168.137.105:7000
redis.port=''
redis.prefix=gv:

[develop : common]
database.driver='mysql'
;database.host='139.162.105.132'
;database.host='mysql'
database.host='dbs'
database.port='3306'
database.database='gv'
database.username='root'
database.password='root'
;database.password='root'
database.charset='utf8'
database.collation='utf8_unicode_ci'
database.prefix='ks_'
database.strict=false
;redis
redis.host.0=rediss
redis.port=6379
redis.prefix=gv:

[test : common]
database.driver='mysql'
database.read.host='139.162.66.189'
database.write.host='139.162.66.189'
;database.read.host='127.0.0.1'
;database.write.host='127.0.0.1'
database.port='3306'
database.database='bluegv'
database.username='root'
database.password='pArm*%anEntF]'
database.charset='utf8'
database.collation='utf8_unicode_ci'
database.prefix='ks_'
database.strict=false
;redis
redis.host.0=127.0.0.1
redis.port=6379
redis.prefix=gv:
