<?php importView("header.phtml"); ?><body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {margin-right: 30px}</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">

                                                    <div class="layui-inline">
                                <label class="layui-form-label">id</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[id]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">uuid</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[uuid]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">当月推广业绩元</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[tui_total]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">视频收益统计</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[mv_coins]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">视频数量</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[mv_number]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">月度日期</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[date_month]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">创作者等级</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[level_num]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                    <div class="layui-inline">
                                <label class="layui-form-label">保级</label>
                                <div class="layui-input-block">
                                                                            <input type="text" name="search[before_level_num]" placeholder="请输入" autocomplete="off" class="layui-input">
                                                                    </div>
                            </div>
                                                <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-edit-dialog">
                                添加
                            </button>
                            <button class="layui-btn layui-btn-sm" lay-event="delSelect" data-pk="id">删除所选</button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-xs" lay-event="info" lay-form="user-data-dialog">信息</a>
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.id}}"  lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-edit-dialog" data-w="900" layer-dialog="确认,取消"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
                                

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">uuid：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="uuid" name="uuid"
                                                                                                    value="{{=d.uuid }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">当月推广业绩元：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="当月推广业绩元" name="tui_total"
                                                                                                    value="{{=d.tui_total }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频收益统计：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="视频收益统计" name="mv_coins"
                                                                                                    value="{{=d.mv_coins }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频数量：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="视频数量" name="mv_number"
                                                                                                    value="{{=d.mv_number }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">月度日期：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="月度日期" name="date_month"
                                                                                                    value="{{=d.date_month }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="创作者等级" name="level_num"
                                                                                                    value="{{=d.level_num }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                    

            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">保级：</label>
                    <div class="layui-input-inline">

                                                    <input lay-verify="required" placeholder="保级" name="before_level_num"
                                                                                                    value="{{=d.before_level_num }}" class="layui-input">
                        
                    </div>
                </div>
            </div>
                <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.id}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>
<script type="text/html" class="data-dialog" id="user-data-dialog" data-w="900"
        data-option="{title:false,closeBtn:false,shadeClose:true,anim:3,offset:'rt',full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form" action="" lay-filter="form-save">
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">id：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.id }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">uuid：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.uuid }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">当月推广业绩元：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.tui_total }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频收益统计：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.mv_coins }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">视频数量：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.mv_number }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">月度日期：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.date_month }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">创作者等级：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.level_num }}" class="layui-input">
                    </div>
                </div>
            </div>
                    <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">保级：</label>
                    <div class="layui-input-inline">
                        <input disabled value="{{=d.before_level_num }}" class="layui-input">
                    </div>
                </div>
            </div>
            </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: '<?php echo url_backend("delAll") ?>',
        uploadUrl: undefined,
        title: '数据表',
        pk: 'id',
        cols: [[
            {type: 'checkbox', fixed: 'left'}
                        , {field: 'id', title: 'id'}
                        , {field: 'uuid', title: 'uuid'}
                        , {field: 'tui_total', title: '当月推广业绩元'}
                        , {field: 'mv_coins', title: '视频收益统计'}
                        , {field: 'mv_number', title: '视频数量'}
                        , {field: 'date_month', title: '月度日期'}
                        , {field: 'level_num', title: '创作者等级'}
                        , {field: 'before_level_num', title: '保级'}
                        , {fixed: 'right', width: 200, title: '操作',align:'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<?php echo \Layui::renderJs() ?><?php importView("fooler.phtml"); ?>