<?php importView("header.phtml"); ?>
    <body>

<!-- 页面加载loading -->
<div class="page-loading">
    <div class="ball-loader">
        <span></span><span></span><span></span><span></span>
    </div>
</div>

<style>.layui-form.form-dialog .layui-input-block {margin-right: 30px}</style>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">管理</div>
                <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                    <div class="layui-form-item">
                        <div class="layui-inline">
                            <label class="layui-form-label">管理员名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="search[username]" placeholder="请输入管理员名称" autocomplete="off"
                                       class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="search">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </div>


                <div class="layui-card-body">
                    <table class="layui-hide" id="gridTab" lay-filter="table-toolbar"></table>
                    <script type="text/html" id="toolbar">
                        <div class="layui-btn-container">
                            <button class="layui-btn layui-btn-sm" lay-event="addUser" lay-form="user-add-dialog">
                                添加
                            </button>
                        </div>
                    </script>
                    <script type="text/html" id="operate-toolbar">
                        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit" lay-form="user-edit-dialog">
                            <i class="layui-icon layui-icon-edit"></i>修改</a>
                        <a class="layui-btn layui-btn-danger layui-btn-xs" data-pk="{{=d.uid}}" lay-event="del">
                            <i class="layui-icon layui-icon-delete"></i>删除</a>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/html" class="data-dialog" id="user-add-dialog" data-h="700" data-w="500" layer-dialog="确认,取消"
        data-option="{closeBtn:false,shadeClose:true,anim:3,full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">用户名：</label>
            <div class="layui-input-inline">
                <input lay-verify="required" placeholder="username" name="username"
                       value="{{=d.username }}" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">密码：</label>
            <div class="layui-input-inline">
                <input placeholder="password" name="password" type="password" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">角色：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('_role_id', AdminRoleModel::getRoleArray(),
                    ['data-value' => '{{d._role_id}}']) ?>
            </div>
        </div>
        {{# if( d.id ){ }}
        {{# }else{ }}
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">标记：</label>
                <div class="layui-input-inline">
                    <input style="color: red" lay-verify="required" placeholder="标记" name="flag"
                           value="{{=d.flag }}" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">密钥：</label>
                <div class="layui-input-inline">
                    <input style="color: red" lay-verify="required" placeholder="密钥" name="secret"
                           value="{{=d.secret }}" class="layui-input">
                </div>
            </div>

        </div>
        {{# } }}

        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.uid}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script type="text/html" class="data-dialog" id="user-edit-dialog" data-h="700" data-w="500" layer-dialog="确认,取消"
        data-option="{closeBtn:false,shadeClose:true,anim:3,full:false}">
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>信息</legend>
    </fieldset>
    <form class="layui-form form-dialog" action="" lay-filter="form-save">
        <div class="layui-form-item">
            <label class="layui-form-label">用户名：</label>
            <div class="layui-input-inline">
                <input lay-verify="required" placeholder="username" name="username"
                       value="{{=d.username }}" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">密码：</label>
            <div class="layui-input-inline">
                <input placeholder="password" name="password" type="password" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label">角色：</label>
            <div class="layui-input-inline">
                <?php echo Layui::select('role_id', AdminRoleModel::getRoleArray(),
                    ['data-value' => '{{d._role_id}}']) ?>
            </div>
        </div>


        <div class="layui-form-item layui-hide">
            <input type="hidden" name="_pk" value="{{=d.uid}}">
            <button class="layui-btn submit" lay-submit="" lay-filter="save"></button>
        </div>

    </form>
</script>

<script>
    xx.use({
        url: '<?php echo url_backend("listAjax") ?>',
        saveUrl: '<?php echo url_backend("save") ?>',
        delUrl: '<?php echo url_backend("del") ?>',
        delALlUrl: undefined,
        uploadUrl: undefined,
        title: '数据表',
        pk: 'uid',
        cols: [[
             {field: 'uid', title: 'uid'}
            , {field: 'flag', title: '标识'}
            // , {field: 'oauth_id', title: 'oauth_id'}
            // , {field: 'uuid', title: 'uuid'}
            , {field: 'username', title: 'username'}
            // , {field: 'password', title: 'password'}
            // , {field: 'role_id', title: 'role_id'}
            , {field: 'role_name', title: '角色'}
            // , {field: 'gender', title: 'gender'}
            // , {field: 'regip', title: 'regip'}
            // , {field: 'regdate', title: 'regdate'}
            , {field: 'lastip', title: 'lastip'}
            , {field: 'lastvisit', title: 'lastvisit'}
            // , {field: 'expired_at', title: '会员到期时间'}
            // , {field: 'lastpost', title: 'lastpost'}
            // , {field: 'oltime', title: '在线小时数'}
            // , {field: 'login_task', title: '是否领取7日任务'}
            // , {field: 'pageviews', title: '论坛用的,电影可以不用'}
            // , {field: 'score', title: '用户积分'}
            // , {field: 'aff', title: '邀请码md5( md5(uuid) )'}
            // , {field: 'invited_by', title: '被谁 aff 邀请'}
            // , {field: 'invited_num', title: '已邀请安装个数'}
            // , {field: 'newpm', title: 'newpm'}
            // , {field: 'new_comment_reply', title: 'new_comment_reply'}
            // , {field: 'new_topic_reply', title: 'new_topic_reply'}
            // , {field: 'login_count', title: 'login_count'}
            // , {field: 'app_version', title: 'app版本号'}
            , {field: 'validate', title: '状态', type: "switch", "value": "1|0", edit: true}
            , {fixed: 'right', width: 200, title: '操作', align: 'center', toolbar: '#operate-toolbar'}
        ]]
    });
</script>
<script type="text/javascript" src="<?php echo LAY_UI_STATIC ?>/data-list.js"></script>
<?php importView("fooler.phtml"); ?>