<script type="text/html" id="member-basis" >
    <div class="table-member">
        <a href="{{d.member_thumb}}" target="_blank"><img src="{{d.member_thumb}}"/></a>
        <p>
            <span>{{d.member_nickname}} <i>{{d.member_phone}}</i></span>
            <em>{{d.member_uuid}}</em>
        </p>
    </div>
</script>
<style type="text/css">
    .layui-table-cell , .operate-toolbar{font-size: 12px;height: auto;line-height: revert;}
    .operate-toolbar a{color: #0e9aef;cursor: pointer;}
    .operate-toolbar a:hover{text-underline: #0e9aef;color: #0775b6;}
</style>
</body>
</html>