<?php include __DIR__ . "/../layout/header.phtml"; ?>
<div class="col-sm-12">
    <div class="ibox float-e-margins">
        <div class="ibox-content">
            <form class="form-horizontal" id="frm">
                <div class="form-group">
                    <label class="col-sm-3 control-label">版本号：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="版本号" class="form-control" name="version"
                               value="<?= $data['version'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">地址：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="地址" class="form-control" id="username" name="apk"
                               value="<?= $data['apk'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">平台：</label>
                    <select id="type" name="type">
                        <option value="">选择</option>
                        <option value="android" <?php if ($data['type'] == 'android'): ?> selected <?php endif; ?> >安卓
                        </option>
                        <option value="ios" <?php if ($data['type'] == 'ios'): ?> selected <?php endif; ?> >苹果</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">更新：</label>
                    <select id="type" name="must">
                        <option value="">选择</option>
                        <option value="1" <?php if ($data['type'] == '1'): ?> selected <?php endif; ?> >强更</option>
                        <option value="0" <?php if ($data['type'] == '0'): ?> selected <?php endif; ?> >软更</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">状态：</label>

                    <div class="col-sm-8">
                        <select name="status" id="status">
                            <option value="">选择</option>
                            <option value="1" <?php if ($data['status'] == 1): ?> selected <?php endif; ?> >启用</option>
                            <option value="2" <?php if ($data['status'] == 2): ?> selected <?php endif; ?> >禁用</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">说明：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="简要说明" class="form-control" name="tips"
                               value="<?= $data['tips'] ?? ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">渠道标识：</label>

                    <div class="col-sm-8">
                        <input type="text" placeholder="渠道标识" class="form-control" name="via"
                               value="<?= $data['via'] ?? ''; ?>">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                        <button class="btn btn-sm btn-white" type="button" onclick="handleEdit()">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    var index = parent.layer.getFrameIndex(window.name);
    var transFile = 0;
    $('#img_url').click(
        function () {
            transFile = 1;
        }
    );

    function handleEdit() {
        var formData = new FormData($("#frm")[0]);
        formData.append('id', "<?=$_GET['id']?>");
        $.ajax({
            url: '/d.php?mod=version&code=doEdit',
            data: formData,
            type: 'POST',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (res) {
                if (res.status == 1) {
                    parent.reload(res.data)
                    parent.layer.close(index)

                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }

</script>
<?php include __DIR__ . "/../layout/footer.phtml"; ?>
