<?php include __DIR__ . "/../layout/header.phtml"; ?>
<div class="row">
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>版本管理    </h5>
                <h5><a  onclick="handleEdit(0);">         &nbsp;&nbsp;&nbsp;添加版本</a></h5>
            </div>
            <div class="ibox-content">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>版本</th>
                        <th>类型</th>
                        <th>下载地址</th>
                        <th style="max-width: 400px;">描述</th>
                        <th>更新</th>
                        <th>时间</th>
                        <th>渠道</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($topic as $key => $v) { ?>
                        <tr>
                            <td><?php echo $v['id'] ?></td>
                            <td><?php echo htmlspecialchars($v['version']) ?></td>
                            <td>
                              <?php echo VersionModel::TYPE[$v['type']] ?>
                            </td>
                            <td>
                                <?php echo $v['apk'] ?>
                            </td>
                            <td><?php echo htmlspecialchars($v['tips']) ?></td>
                            <td><?php echo VersionModel::MUST[$v['must']] ?></td>

                            <td><?php echo date('Y-m-d H:i',$v['created_at'] )?></td>
                            <td><?php echo $v['via'] ?></td>
                            <td>
                                <?php if ($v['status']==2){ ?><a class="btn btn-xs btn-danger">禁用</a><?php } ?>
                                <?php if ($v['status']==1){ ?><a class="btn btn-xs btn-success">启用</a><?php } ?>
                            </td>
                            <td>
                                <a onclick="handleEdit(<?php echo $v['id'] ?>)" class="btn btn-xs btn-primary">编辑</a>

                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <?= $page_arr['html']; ?>
            </div>
        </div>
    </div>

</div>
<script src="/static/admin/js/jquery.md5.js"></script>
<script>


    function layerOpen(url, title) {
        layer.open({
            type: 2,
            title: title,
            closeBtn: 1,
            shadeClose: true,
            shade: [0.5],
            area: ['800px', '800px'],
            content: url
        })
    }

    function getAjax(url) {
        $.ajax({
            url: url,
            type: 'GET',
            success: function (res) {
                if (res.status == 1) {
                    layer.msg(res.data, {icon: 1})
                } else {
                    layer.msg(res.data, {icon: 5})
                }
            }
        })
    }

    function reload(msg) {
        parent.layer.msg(msg, {icon: 1})
        window.location.reload()
    }


    function handleEdit(id) {
        var url = "d.php?mod=version&code=edit&id=" + id;
        layerOpen(url, '添加/编辑')
    }

</script>
<?php include __DIR__ . "/../layout/footer.phtml"; ?>
