[common]
application.dispatcher.throwException=1
application.dispatcher.catchException=1
application.directory = APP_PATH "/application"
application.bootstrap=APP_PATH "/application/bootstrap/Bootstrap.php"
application.modules = "Index,Home,Api,Admin,Script,V2,Live"
application.dispatcher.defaultModule = 'Home'
application.dispatcher.defaultController = 'Forward'
application.library.namespace = "App"
;user
user.default_filter='trim,addslashes,htmlspecialchars'
token.login=e096db7c006958f226bc469c27237345

img.img_av_url=https://images.91tv.tv/img.av/
img.img_live_url=https://images.91tv.tv/img.live/
img.img_xiao_url=https://images.91tv.tv/
img.img_actors_url=https://images.91tv.tv/img.actors/
img.img_head_url=https://images.91tv.tv/img.head/
img.img_ads_url=https://images.91tv.tv/img.ads/
img.img_icos_url=https://images.91tv.tv/img.icos/
img.img_music_url=https://p.cnkamax.com/
img.default_jd_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91nolog_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
img.default_91login_thumb=http://images.91tv.tv/new/head/20200729/2020072920265415312.jpeg
;sms
sms.timeout=120
; user can watch count
; 页面
site.long_video_duration=30
site.can_watch_count = 10
template.compiled_root_path = /data/cache/tpl/
template.template_path = tpl
template.template_root_path = /theme/

;官方群
official.group='https://ptcc.in/gtvlive'
; 联盟id
union.pid=
; 联盟加解密key
union.key=""
; 联盟签名key
union.sign=""
; 联盟消息存放在redis中的消息队列name
union.qname=""
;  日志等级。最高16，最低0，调试时使用16，正式环境日志等级使用 9 ，不需要日志 0
union.log_level=9

;redis
redis.host.0=rediss
redis.port=6379
redis.prefix=gv:

