[common]
## 同步数据
spider_sync.driver = "mysql"
spider_sync.read.host = "dbs"
spider_sync.write.host = "dbs"
spider_sync.port = "3306"
spider_sync.database = "gv"
spider_sync.username = "root"
spider_sync.password = "root"
spider_sync.charset = "utf8mb4"
spider_sync.collation = "utf8mb4_general_ci"
spider_sync.prefix = "ks_"
spider_sync.strict = false
